"""LeanDojo-v2 adapter utilities for tracing and theorem extraction."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any
import importlib
import logging
import os

from physlean_bench.schemas import TracedTheoremInfo

logger = logging.getLogger(__name__)


@dataclass
class LeanDojoTraceResult:
    traced_repo_root: Path
    tracing_tool: str
    tracing_tool_version: str
    theorem_count: int


def _dedupe_preserve_order(values: list[str]) -> list[str]:
    seen: set[str] = set()
    deduped: list[str] = []
    for value in values:
        if value in seen:
            continue
        seen.add(value)
        deduped.append(value)
    return deduped


def _extract_imports_from_file(path: Path) -> list[str]:
    imports: list[str] = []
    if not path.exists():
        return imports

    in_block_comment = False
    for line in path.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if not stripped:
            continue
        if in_block_comment:
            if "-/" in stripped:
                in_block_comment = False
            continue
        if stripped.startswith("/-"):
            if "-/" not in stripped:
                in_block_comment = True
            continue
        if stripped.startswith("--"):
            continue
        if stripped == "prelude":
            continue
        if stripped.startswith("import "):
            modules = stripped[len("import ") :].split()
            imports.extend(modules)
            continue
        # Lean import block is expected near the file start; once regular code starts,
        # stop collecting imports to avoid false positives from comments/strings.
        break
    return _dedupe_preserve_order(imports)


def _slice_by_pos(source_text: str, start_line: int, start_col: int, end_line: int, end_col: int) -> str:
    """Slice Lean source using 1-based line/column positions."""
    lines = source_text.splitlines()
    if start_line < 1 or end_line < start_line:
        return ""
    if end_line > len(lines):
        end_line = len(lines)
    if start_line > len(lines):
        return ""

    if start_line == end_line:
        line = lines[start_line - 1]
        return line[max(start_col - 1, 0) : max(end_col - 1, 0)]

    chunks: list[str] = []
    first = lines[start_line - 1]
    chunks.append(first[max(start_col - 1, 0) :])

    for idx in range(start_line, end_line - 1):
        chunks.append(lines[idx])

    last = lines[end_line - 1]
    chunks.append(last[: max(end_col - 1, 0)])
    return "\n".join(chunks)


def _infer_namespace(full_name: str) -> str:
    if "." not in full_name:
        return ""
    return full_name.rsplit(".", maxsplit=1)[0]


def _infer_kind_from_statement(statement: str) -> str:
    stripped = statement.strip()
    for keyword in ("theorem", "lemma", "def", "instance", "example"):
        if stripped.startswith(keyword + " "):
            return keyword
    return "declaration"


def _is_autogenerated_name(full_name: str) -> bool:
    return full_name.startswith("_") or ".match_" in full_name or ".proof_" in full_name


def _extract_proof_payload(traced_theorem: Any, file_text: str) -> tuple[str | None, str | None]:
    # Prefer LeanDojo's tactic proof extraction when available.
    try:
        tactic_proof = traced_theorem.get_tactic_proof()
    except Exception:
        tactic_proof = None
    if tactic_proof:
        return tactic_proof.strip(), "lean_dojo_tactic_proof"

    try:
        proof_start, proof_end = traced_theorem.locate_proof()
        proof_text = _slice_by_pos(
            file_text,
            proof_start.line_nb,
            proof_start.column_nb,
            proof_end.line_nb,
            proof_end.column_nb,
        ).strip()
    except Exception:
        proof_text = ""

    if proof_text:
        return proof_text, "source_span"
    return None, None


def trace_with_leandojo_v2(
    repo_dir: Path,
    *,
    cache_dir: Path,
    tmp_dir: Path,
    build_deps: bool,
    lake_binary: Path | None,
) -> tuple[Any, str]:
    """Trace repo with LeanDojo-v2 and return a TracedRepo object plus version string."""
    repo_dir = repo_dir.resolve()
    cache_dir = cache_dir.resolve()
    tmp_dir = tmp_dir.resolve()
    cache_dir.mkdir(parents=True, exist_ok=True)
    tmp_dir.mkdir(parents=True, exist_ok=True)

    os.environ["CACHE_DIR"] = str(cache_dir)
    os.environ["TMP_DIR"] = str(tmp_dir)

    if lake_binary is not None:
        os.environ["PATH"] = f"{lake_binary.parent}:{os.environ.get('PATH', '')}"

    try:
        lean_dojo = importlib.import_module("lean_dojo")
    except Exception as exc:
        raise RuntimeError(
            "LeanDojo import failed. Install it with `pip install lean-dojo` in your runtime env."
        ) from exc

    LeanGitRepo = getattr(lean_dojo, "LeanGitRepo")
    trace = getattr(lean_dojo, "trace")

    lean_repo = LeanGitRepo.from_path(repo_dir)
    traced_repo = trace(lean_repo, dst_dir=None, build_deps=build_deps)
    version = str(getattr(lean_dojo, "__version__", "unknown"))
    return traced_repo, version


def extract_traced_theorems(
    traced_repo: Any,
    *,
    include_prefixes: list[str],
    exclude_prefixes: list[str],
) -> list[TracedTheoremInfo]:
    """Convert LeanDojo traced theorem objects to physlean-bench schema records."""
    include_prefixes = include_prefixes or ["Physlib/"]
    exclude_prefixes = exclude_prefixes or []

    records: list[TracedTheoremInfo] = []

    file_import_cache: dict[Path, list[str]] = {}
    file_premise_cache: dict[Path, list[str]] = {}

    for traced_file in traced_repo.traced_files:
        rel_path = Path(str(traced_file.path))
        rel_text = rel_path.as_posix()

        if include_prefixes and not any(rel_text.startswith(prefix) for prefix in include_prefixes):
            continue
        if any(rel_text.startswith(prefix) for prefix in exclude_prefixes):
            continue

        abs_file_path = traced_repo.root_dir / rel_path
        if rel_path not in file_import_cache:
            file_import_cache[rel_path] = _extract_imports_from_file(abs_file_path)

        if rel_path not in file_premise_cache:
            try:
                premises_data = traced_file.get_premise_definitions()
                file_premise_cache[rel_path] = _dedupe_preserve_order(
                    [
                        str(item.get("full_name", ""))
                        for item in premises_data
                        if str(item.get("full_name", "")).strip()
                    ]
                )
            except Exception:
                file_premise_cache[rel_path] = []

        source_text = abs_file_path.read_text(encoding="utf-8") if abs_file_path.exists() else ""
        for traced_theorem in traced_file.get_traced_theorems():
            full_name = str(getattr(traced_theorem.theorem, "full_name", ""))
            namespace = _infer_namespace(full_name)
            module_path = rel_path.with_suffix("").as_posix().replace("/", ".")

            try:
                statement = traced_theorem.get_theorem_statement().strip()
            except Exception:
                statement = ""

            proof_text, proof_method = _extract_proof_payload(traced_theorem, source_text)
            kind = _infer_kind_from_statement(statement)
            if hasattr(traced_theorem, "ast") and hasattr(traced_theorem.ast, "kind"):
                try:
                    kind = str(traced_theorem.ast.kind())
                except Exception:
                    pass

            used_premises: list[str] = []
            try:
                used_premises = _dedupe_preserve_order(
                    [str(item) for item in traced_theorem.get_premise_full_names() if str(item).strip()]
                )
            except Exception:
                used_premises = []

            has_sorry = "sorry" in statement or (proof_text is not None and "sorry" in proof_text)
            has_admit = "admit" in statement or (proof_text is not None and "admit" in proof_text)

            records.append(
                TracedTheoremInfo(
                    theorem_id=str(getattr(traced_theorem.theorem, "uid", full_name)),
                    declaration_name=full_name,
                    namespace=namespace,
                    module_path=module_path,
                    file_path=rel_text,
                    statement=statement,
                    proof_text=proof_text,
                    imports=file_import_cache[rel_path],
                    declaration_kind=kind,
                    has_sorry=has_sorry,
                    has_admit=has_admit,
                    is_auto_generated=_is_autogenerated_name(full_name),
                    accessible_premises=file_premise_cache[rel_path],
                    used_premises=used_premises,
                    line_start=int(traced_theorem.start.line_nb),
                    line_end=int(traced_theorem.end.line_nb),
                    tags=["leandojo_v2", "real_trace"],
                    trace_backend="leandojo_v2",
                    proof_extraction_method=proof_method,
                )
            )

    return records
